name: Deployment Exsercise 2
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checking code
      run: echo "Checking code"
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying code
      run: echo "Deploying code"
